{% set version = "0.3.2" %}

package:
  name: ezodf
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/e/ezodf/ezodf-{{ version }}.tar.gz
  sha256: 000da534f689c6d55297a08f9e2ed7eada9810d194d31d164388162fb391122d

build:
  number: 3
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - lxml

test:
  requires:
    - python {{ python_min }}
  imports:
    - ezodf

about:
  home: https://github.com/T0ha/ezodf
  license_file: LICENSE.txt
  license: MIT
  license_family: MIT
  summary: 'A Python package to create/manipulate OpenDocumentFormat files'
  dev_url: https://github.com/T0ha/ezodf

extra:
  recipe-maintainers:
    - pmlandwehr
    - ocefpaf
