travis:
  secure:
    BINSTAR_TOKEN: Rt/J0dZW59qWOLJoEgmIB/EwX3eCmfqliQ3ddV+/EWhnHH6OHtimEi8U+3cbAZFQ4wlqi15x96xo4jCNUYeIgeDWf5OY7NtnakZnU/gGVBub8Jh6V7ORwTZHy3rqDDan13A9rmd+6ZS9IAuYUd9GSVNvft10AP1gcSEZ6RdEeYXoneGNWrzYg1fpXrnuDkhhh1fkFrVqeOXe5QQRU6N//cpKs65XP6Io9DMDNys2/s0PwBPiBBlIJg3GvG7z2ZtKL2bjv5I7yXgfnaftPHU6eGnA/eWCsDlskEXX6eqYgGjbsO3YslwhMu2pSXFU7lfLrtvZHSOiBGzHtYMOwUTUKu61S0nxmfrSyIbLM/Qbf7/omYgZOky3jlUq+gPhakDO8Ph9vp9kPMEuHmRl7KJML0/s9ntv1jJdbZ078ncJQUvWx0JmOcaUzvO6nADjaFy1NxrhNuW5A1S22saEDslJpyoQvTe2QnIEuCCxYgBUGBcys4PomjQxQWIMIyFiU3vvh6UrrJs4fzhe6Vtrhq8I0N9zhmEwc+Qoc6rsLP48Ei85f0t1EwnKsGTPcE89HHy5NVvfdnE5qMd8E3LTt0YmzLzLR52q0T7zBV6Lv8QOQv/S54wUuI5OPhR7kRZcBBCv10A6XEMq9VPJYfsxtWBK6nDHiTx8Nd05aaUStEm0h5I=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
