travis:
  secure:
    BINSTAR_TOKEN: hIVWMqrdK+y4eMHwbtvyw+ssDRDxqbyH8ZcxJACUg5PwKIcxRgxsAzsu0ROPrw6vaM4YKiQVjgnYs/B8OdsGOjeCvBYzLfxZlMlJW5qJZqxpOmEktQxqM2L906VYvZGE3A0Uuhesoe1zTofnPXEAWZXK/x89LBdil8baKV/ptSer0wWo78G+llOoOd384vsi6j5i6o/NXNi7WhEHh4Oky1yp1k7edmEZFID0sigHZjP+krTddFlMoIIVg8tgWRDltbiq0suqLKXu/xh9T0330W+NqeoSVLCTccaOtpVSx00yRCptB/9wMBQNfj3n4JSmGMfsaSReqPn2tWXA4NAQ9+9FiNM1RF5lcOBA/hStQvLlDoCl8RTtKYYV4NguMCb85yVLp0rYFkxrABHPbjCX9joEIOg5zdTfNnRiUQtOm0t/VF7uNkF3dGnWJy+QWqxgoNgVQYuqe20YYBm3GCdgkVv8FZd2Ekde9ewGpdwfUJV/1uWKd2S671zMT0mFn7i8j6EayeaXGVbcqmOmuhoU/K972DIigASKMLHsTBpg5RnBQc/wqPgjpgaC1IzqkVEDrBXuBBgR0BRXBwmMWQkCpDEVgrcO/3Yvism02IEfN5YIN3cTxcIoOxIHtceM77NTtAvKooyCCgnhJ2OVJQOvfznW4jCfkn3BoMnczPPUTzA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
